backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Categorie"
      name: "category"
      file: "content/category.md"
      fields:
        - label: 'Categories'
          name: "categories"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - label : "Produits"
              name : 'products'
              widget: list
              fields:
                - { label: "Name", name: "name", widget: "string"}
                - { label: "Miniature", name: "thumbnail", widget: "image" , allow_multiple : false}
                - { label: "Prix", name: "price", widget: "number", value_type: 'float'}
                - { label: "Description", name: "description", widget: "text"}
                - {label : "Image" , name: "image" , widget: "image" , mu}





