backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Les categories"
        name: "category"
        file: "content/category.md"
        fields:
          - label: "Categories"
            name: "categories"
            widget: list
            fields:
              - { label: "Nom de la categorie", name: "name", widget: "string" }

      - label: "Les produits"
        name: "products"
        file: "content/products.md"
        fields:
          - label: "Produits"
            name: "products"
            widget: list
            fields:
              - label: "Product Name"
                name: "name"
                widget: string
              - label: "Product Category"
                name: "category"
                widget: relation
                collection: "pages"
                file: "category"
                value_field: "categories.*.name"
                display_fields: ["categories.*.name"]
                search_fields: ["categories.*.name"]
              - { label: "Miniature", name: "thumbnail", widget: "image" }
              - {
                  label: "Prix",
                  name: "price",
                  widget: "number",
                  value_type: "float",
                }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Colors"
                name: "colors"
                widget: list
                fields:
                  - { label: "Color", name: "color", widget: "color" }
              - label: "Sizes"
                name: "sizes"
                widget: list
                fields:
                  - label: "Size"
                    name: "size"
                    widget: "select"
                    options: ["S", "M", "L", "XL", "none"]
              - label: "Images"
                name: "images"
                widget: list
                fields:
                  - { label: "Image", name: "image", widget: "image" }
