backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "Shipping"
    label: "Expédition"
    files:
      - label: "Wilaya / tarif de livraison"
        name: "wilaya"
        file: "content/wilaya.md"
        fields:
          - label: "wilayas"
            name: "wilaya"
            widget: list
            fields:
              - label: "Align Content"
                name: "align"
                widget: "select"
                options:
                  [
                    "Adrar ",
                    "Chlef ",
                    "Laghouat ",
                    "Oum El Bouaghi ",
                    "Batna ",
                    "Béjaïa ",
                    "Biskra ",
                    "Béchar ",
                    "Blida ",
                    "Bouïra ",
                    "Tamanrasset ",
                    "Tébessa ",
                    "Tlemcen ",
                    "Tiaret ",
                    "Tizi Ouzou ",
                    "Algiers ",
                    "Djelfa ",
                    "Jijel ",
                    "Sétif ",
                    "Saïda ",
                    "Skikda ",
                    "Sidi Bel Abbès ",
                    "Annaba ",
                    "Guelma ",
                    "Constantine ",
                    "Médéa ",
                    "Mostaganem ",
                    "M'Sila ",
                    "Mascara ",
                    "Ouargla ",
                    "Oran ",
                    "El Bayadh ",
                    "Illizi ",
                    "Bordj Bou Arréridj ",
                    "Boumerdès ",
                    "El Taref ",
                    "Tindouf ",
                    "Tissemsilt ",
                    "El Oued ",
                    "Khenchela ",
                    "Souk Ahras ",
                    "Tipaza ",
                    "Mila ",
                    "Aïn Defla ",
                    "Naâma ",
                    "Aïn Témouchent ",
                    "Ghardaïa ",
                    "Relizane ",
                    "El M'Ghair ",
                    "El Menia ",
                    "Ouled Djellal ",
                    "Bordj Baji Mokhtar ",
                    "Béni Abbès ",
                    "Timimoun ",
                    "Touggourt ",
                    "Djanet ",
                    "In Salah ",
                    "Ain Guezzam ",
                  ]
                required: true

              - {
                  label: "Tarif de livraison",
                  name: "tax",
                  widget: "number",
                  value_type: "float",
                }
  - name: "pages"
    label: "Pages"
    files:
      - label: "Les categories"
        name: "category"
        file: "content/category.md"
        fields:
          - label: "Categories"
            name: "categories"
            widget: list
            fields:
              - { label: "Nom de la categorie", name: "name", widget: "string" }

      - label: "Les produits"
        name: "products"
        file: "content/products.md"
        fields:
          - label: "Produits"
            name: "products"
            widget: list
            fields:
              - label: "Product Name"
                name: "name"
                widget: string
              - label: "Product Category"
                name: "category"
                widget: relation
                collection: "pages"
                file: "category"
                value_field: "categories.*.name"
                display_fields: ["categories.*.name"]
                search_fields: ["categories.*.name"]
              - { label: "Miniature", name: "thumbnail", widget: "image" }
              - {
                  label: "Prix",
                  name: "price",
                  widget: "number",
                  value_type: "float",
                }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Colors"
                name: "colors"
                widget: list
                fields:
                  - { label: "Color", name: "color", widget: "color" }
              - label: "Sizes"
                name: "sizes"
                widget: list
                fields:
                  - label: "Size"
                    name: "size"
                    widget: "select"
                    options: ["S", "M", "L", "XL", "none"]
              - label: "Images"
                name: "images"
                widget: list
                fields:
                  - { label: "Image", name: "image", widget: "image" }
