import WrapperComponent from '../components/WrapperComponent'
import Head from "next/head";
import { useState } from 'react';
export default function Home() {

    const [visible, setVisible] = useState(false);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <WrapperComponent visible={visible} setVisible={setVisible} />

        </>
    );
}
