import Head from "next/head";
import Carousel_component from "../components/Carousel";
import Hero from "../components/Hero";
import Productslist from "../components/Productslist";
import Header from "../components/Header";
import { useState } from "react";

export default function Home() {
    const [selectedProducts, setselectedProducts] = useState([]);
    const [total_sum, settotal_sum] = useState(0);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header list={selectedProducts} total={total_sum} settotal={settotal_sum} setlist={setselectedProducts} />
            <div className="">
                <Hero />
                <Carousel_component />
                <Productslist settotal={settotal_sum} val={selectedProducts} selected={setselectedProducts} />
            </div>
        </>
    );
}
